### PR TITLE
Add Web3js docs

### PR DESCRIPTION
**Pull request by avkos**
## Description

What changes are made in this PR? Is it a feature or a bug fix?

## Additional Information

Before submitting this issue, please make sure you do the following.

- [ ] Read the [contributing guide](https://wagmi.sh/dev/contributing)
- [ ] Added documentation related to the changes made.
- [ ] Added or updated tests (and snapshots) related to the changes made.

### CODE REVIEW

**Comment by luu-alex** [comment]
Looks good

**Comment by tmm** [comment]
Appreciate this PR! Going to close it as Web3.js isn't popular among Wagmi users. Good news is folks will be able to reference the code in this PR if they are using Web3.js. At some point in the future, can revisit whether this is needed in the docs.

**Comment by avkos** [comment]
Hey @tmm,

Thanks for your consideration. I understand the rationale behind closing the PR, but I believe it's valuable to offer users the flexibility to choose their preferred tools. Providing documentation on how to use Wagmi with Web3.js could benefit those who opt for this route.

Here's a resource outlining how Wagmi can be integrated with Web3.js: [Wagmi with Web3.js documentation](https://docs.web3js.org/guides/wagmi_usage/wagmi).

By including this, we empower users with more options and ensure inclusivity within our community. Let's keep the door open for diverse approaches.

Cheers!

**Comment by avkos** [comment]
Also, I found [a discussion](https://github.com/wevm/wagmi/discussions/1733) that suggests there's interest in having this documentation. Hope you make the right decision, thanks!

**Pull request closed without merging**
