### PR TITLE
beta

### PR DESCRIPTION
**Pull request by tmm**
`wagmi@beta`

related [`viem@beta`](https://github.com/wagmi-dev/viem/pull/1429)

### CODE REVIEW

**Comment by cruzdanilo** [comment]
i'm not sure if this is the place to report bugs in the beta. please, let me know otherwise.

when using `@wagmi/cli` `2.0.0-beta.5`, i get this error:
```log
node_modules/@wagmi/cli/dist/esm/commands/generate.js:7
import { ensureDir, writeFile } from 'fs-extra';
                    ^^^^^^^^^
SyntaxError: Named export 'writeFile' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fs-extra';
const { ensureDir, writeFile } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async loadESM (node:internal/process/esm_loader:42:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.6.1
```

**Comment by tmm** [comment]
@cruzdanilo Can create an issue!

**Comment by glitch-txs** [comment]
Hi Tom, can we remove required chains/methods/events from WalletConnect connector here in v2?
Also all events/methods are defaulted in optional namespaces.

**Comment by tmm** [comment]
closing in favor of https://github.com/wevm/wagmi/pull/3333

**Pull request closed without merging**
